// Auto-generated by export_research_to_site.py — DO NOT EDIT
// Generated: 

export interface Paper {
  id: string;
  title: string;
  authors: string[];
  venue: string;
  year: number;
  link: string;
  pdf_url: string;
  summary: string;
  tags: string[];
  featured: boolean;
}

export interface GitHubRepo {
  name: string;
  owner: string;
  description: string;
  language: string;
  stars: number;
  link: string;
  topics: string[];
}

export interface NewsItem {
  id: string;
  title: string;
  summary: string;
  source: string;
  link: string;
  published_at: string;
  freshness: "fresh" | "aging" | "stale";
}

export const papers: Paper[] = [
  {
    id: "",
    title: "DIAL: Decomposing Vision-Language Models into Intent Understanding and Action Decoding",
    authors: ["Stanford / Berkeley"],
    venue: "arXiv:2603.29844",
    year: 0,
    link: "https://arxiv.org/abs/2603.29844",
    pdf_url: "https://arxiv.org/pdf/2603.29844",
    summary: "VLA架构创新：VLM不应只做编码器，应利用高层意图理解。分为Intent Bottleneck（潜世界模型编码意图）和Action Decoding（潜逆动力学解码动作），实现LLM→VLA→PX4架构解耦。",
    tags: ["VLA", "LLM", "Robot", "Embodied AI", "Intent"],
    featured: false,
  },
  {
    id: "",
    title: "LLM-Enabled UAV NL Navigation: Natural Language to Signal Temporal Logic for Autonomous Flight",
    authors: ["港科大"],
    venue: "arXiv:2603.27583",
    year: 0,
    link: "https://arxiv.org/abs/2603.27583",
    pdf_url: "https://arxiv.org/pdf/2603.27583",
    summary: "自然语言→信号时序逻辑(STL)→MILP轨迹优化。CoT推理+GRPO优化确保翻译正确性，STL修复机制处理不可行约束。已有实机飞行验证。",
    tags: ["LLM", "UAV", "STL", "NLP", "Motion Planning"],
    featured: false,
  },
  {
    id: "",
    title: "CARLA-Air: Unified Aerial-Ground Simulation Infrastructure",
    authors: ["ETH Zurich"],
    venue: "arXiv:2603.28032",
    year: 0,
    link: "https://arxiv.org/abs/2603.28032",
    pdf_url: "https://arxiv.org/pdf/2603.28032",
    summary: "AirSim + CARLA统一到单一Unreal Engine进程，零修改复用AirSim API+ROS 2。18种传感器模态同步采集。完整仿真验证环境，适合毕设仿真验证。",
    tags: ["Simulation", "UAV", "ROS", "CARLA", "Sensor Fusion"],
    featured: false,
  },
  {
    id: "",
    title: "AeroGen: Agentic Drone Autonomy through Single-Shot Structured Prompting",
    authors: ["MIT / UC Berkeley"],
    venue: "arXiv:2603.25000",
    year: 0,
    link: "https://arxiv.org/abs/2603.25000",
    pdf_url: "https://arxiv.org/pdf/2603.25000",
    summary: "PX4 + LLM agent单步结构化提示，一次prompt完成多任务规划。轻量级方案，适合边缘部署。支持语音控制和云端API。",
    tags: ["LLM", "UAV", "PX4", "Agent", "Edge AI"],
    featured: false,
  },
  {
    id: "",
    title: "Realtime-VLA V2: Learning to Run VLAs Fast, Smooth and Accurate",
    authors: ["上海AI Lab"],
    venue: "arXiv:2603.20000",
    year: 0,
    link: "https://arxiv.org/abs/2603.20000",
    pdf_url: "https://arxiv.org/pdf/2603.20000",
    summary: "实时VLA，在边缘设备(Jetson)上快速流畅运行VLAs。EAGLE-3投机解码+NVFP4量化优化，兼顾精度和速度。适合无人机实时性需求。",
    tags: ["VLA", "Real-time", "Edge AI", "Quantization"],
    featured: false,
  },
  {
    id: "",
    title: "FocusVLA: Visual Attention Optimization for Efficient Vision-Language-Action Models",
    authors: ["字节跳动"],
    venue: "arXiv:2603.28740",
    year: 0,
    link: "https://arxiv.org/abs/2603.28740",
    pdf_url: "https://arxiv.org/pdf/2603.28740",
    summary: "VLA瓶颈在于如何利用视觉而非视觉质量本身。提出Modality Cascaded Attention消除快捷路径。边缘部署计算优化参考。",
    tags: ["VLA", "Attention", "Edge AI", "Efficiency"],
    featured: false,
  },
];

export const githubRepos: GitHubRepo[] = [
  {
    name: "PX4 Autopilot",
    owner: "",
    description: "开源无人机自动驾驶软件，支持多旋翼、固定翼、VTOL等。学术界最流行的无人机研究平台。",
    language: "C++",
    stars: 11.8k,
    link: "https://github.com/PX4/PX4-Autopilot",
    topics: [],
  },
  {
    name: "Prometheus (amov-lab)",
    owner: "",
    description: "PX4无人机自主飞行综合解决方案，包含目标追踪、集群控制、SLAM等30+应用模块。累计3.1k+ stars。",
    language: "C++",
    stars: 3.1k,
    link: "https://github.com/amov-lab/Prometheus",
    topics: [],
  },
  {
    name: "embodied-drone-agents",
    owner: "",
    description: "LLM drone agent系统，使用MAVSDK-Python作为工具，LangGraph编排任务规划，支持自然语言控制无人机。",
    language: "Python",
    stars: 22,
    link: "https://github.com/EmergenceAI/embodied-drone-agents",
    topics: [],
  },
  {
    name: "llm-uav (Atmaca)",
    owner: "",
    description: "集成Gemma 3 4B与无人机控制，支持自然语言指令，边缘部署。",
    language: "Python",
    stars: 0,
    link: "https://github.com/furkanisikay/llm-uav",
    topics: [],
  },
  {
    name: "MAVLinkMCP",
    owner: "",
    description: "MCP (Model Context Protocol) server for LLM与MAVLink无人机的通信，支持通过MCP协议控制PX4无人机。",
    language: "Python",
    stars: 16,
    link: "https://github.com/ion-g-ion/MAVLinkMCP",
    topics: [],
  },
  {
    name: "Awesome-RL-VLA",
    owner: "",
    description: "RL+VLA论文汇总：强化学习视觉-语言-动作模型综述。",
    language: "Python",
    stars: 711,
    link: "https://github.com/Denghaoyuan123/Awesome-RL-VLA",
    topics: [],
  },
  {
    name: "Awesome-LLM-Robotics",
    owner: "",
    description: "大语言模型/多模态模型在机器人领域的应用论文汇总。",
    language: "Python",
    stars: 4.4k,
    link: "https://github.com/GT-RIPL/Awesome-LLM-Robotics",
    topics: [],
  },
  {
    name: "Awesome-Aerial-VLN",
    owner: "",
    description: "空中视觉-语言导航(Aerial VLN)论文汇总：无人机VLN方向最新研究。",
    language: "Python",
    stars: 54,
    link: "https://github.com/Sautenich/Awesome-Aerial-Vision-Language-Navigation",
    topics: [],
  },
];

export const news: NewsItem[] = [
  {
    id: "",
    title: "高度相关！",
    summary: "🌤️ ━━━━━━━━━━━━━━━━━━━━━━━━━ 早上好！新的一周开始啦～ 珠海 🌧️ 小雨 +26°C | 湿度 89% | 西风 17km/h",
    source: "GitHub",
    link: "https://github.com/NouResearch/hermes-agent",
    published_at: "2026-05-18",
    freshness: "fresh" as const,
  },
  {
    id: "",
    title: "NVIDIA GR00T N1.6 + Cosmos Reason 2 发布",
    summary: "NVIDIA发布开源物理AI模型GR00T N1.6和Cosmos Reason世界模型，全球合作伙伴推出下一代机器人，机器人的ChatGPT时刻已至。",
    source: "NVIDIA Newsroom",
    link: "https://nvidianews.nvidia.com/news/nvidia-releases-new-physical-ai-models-as-global-partners-unveil-next-generation-robots",
    published_at: "2026-04-01",
    freshness: "fresh" as const,
  },
  {
    id: "",
    title: "Unitree B2-W 四足机器人发布",
    summary: "宇树科技发布B2-W工业四足机器人，负载30kg，续航4小时，支持复杂地形巡检，配备深度相机和激光雷达。",
    source: "Unitree",
    link: "https://www.unitree.com.cn/",
    published_at: "2026-03-25",
    freshness: "fresh" as const,
  },
  {
    id: "",
    title: "DJI Air 3S 无人机发布",
    summary: "大疆发布Air 3S，配备1英寸主摄+70mm长焦双摄系统，全向避障，支持APAS 5.0，续航48分钟，面向消费级航拍市场。",
    source: "DJI",
    link: "https://www.dji.com/cn/air-3s",
    published_at: "2026-03-28",
    freshness: "fresh" as const,
  },
  {
    id: "",
    title: "OpenAI 发布 GPT-4.5 API，扩展上下文窗口",
    summary: "OpenAI向开发者开放GPT-4.5 API，上下文窗口扩展至200k tokens，定价下调40%，强化函数调用和结构化输出能力。",
    source: "OpenAI",
    link: "https://openai.com/index/gpt-4-5-launch",
    published_at: "2026-04-02",
    freshness: "fresh" as const,
  },
];
