// Auto-generated by export_research_to_site.py
// Last updated: 2026-05-04T08:45:45.632819

export interface ResearchPaper {
  title: string;
  authors: string;
  venue: string;
  date: string;
  summary: string;
  link: string;
  pdf_url: string;
  tags: string[];
  importance: string;
}

export interface GitHubProject {
  name: string;
  description: string;
  stars: string;
  language: string;
  link: string;
  tags: string[];
  verified: boolean;
}

export interface NewsItem {
  title: string;
  source: string;
  date: string;
  summary: string;
  link: string;
  published_at: string;
  freshness: string;
  verified: boolean;
  why_it_matters?: string;
  research_axis?: string;
}

export interface Trend {
  icon: string;
  title: string;
  description: string;
}

export const researchPapers: ResearchPaper[] = [
  {
  title: "DIAL: Decomposing Vision-Language Models into Intent Understanding and Action Decoding",
  authors: "Stanford / Berkeley",
  venue: "arXiv:2603.29844",
  date: "2026-03-31",
  summary: "VLA架构创新：VLM不应只做编码器，应利用高层意图理解。分为Intent Bottleneck（潜世界模型编码意图）和Action Decoding（潜逆动力学解码动作），实现LLM→VLA→PX4架构解耦。",
  link: "https://arxiv.org/abs/2603.29844",
  pdf_url: "https://arxiv.org/pdf/2603.29844",
  tags: ["VLA", "LLM", "Robot", "Embodied AI", "Intent"],
  importance: "high"
},
  {
  title: "LLM-Enabled UAV NL Navigation: Natural Language to Signal Temporal Logic for Autonomous Flight",
  authors: "港科大",
  venue: "arXiv:2603.27583",
  date: "2026-03-30",
  summary: "自然语言→信号时序逻辑(STL)→MILP轨迹优化。CoT推理+GRPO优化确保翻译正确性，STL修复机制处理不可行约束。已有实机飞行验证。",
  link: "https://arxiv.org/abs/2603.27583",
  pdf_url: "https://arxiv.org/pdf/2603.27583",
  tags: ["LLM", "UAV", "STL", "NLP", "Motion Planning"],
  importance: "high"
},
  {
  title: "CARLA-Air: Unified Aerial-Ground Simulation Infrastructure",
  authors: "ETH Zurich",
  venue: "arXiv:2603.28032",
  date: "2026-03-30",
  summary: "AirSim + CARLA统一到单一Unreal Engine进程，零修改复用AirSim API+ROS 2。18种传感器模态同步采集。完整仿真验证环境，适合毕设仿真验证。",
  link: "https://arxiv.org/abs/2603.28032",
  pdf_url: "https://arxiv.org/pdf/2603.28032",
  tags: ["Simulation", "UAV", "ROS", "CARLA", "Sensor Fusion"],
  importance: "high"
},
  {
  title: "AeroGen: Agentic Drone Autonomy through Single-Shot Structured Prompting",
  authors: "MIT / UC Berkeley",
  venue: "arXiv:2603.25000",
  date: "2026-03-25",
  summary: "PX4 + LLM agent单步结构化提示，一次prompt完成多任务规划。轻量级方案，适合边缘部署。支持语音控制和云端API。",
  link: "https://arxiv.org/abs/2603.25000",
  pdf_url: "https://arxiv.org/pdf/2603.25000",
  tags: ["LLM", "UAV", "PX4", "Agent", "Edge AI"],
  importance: "high"
},
  {
  title: "Realtime-VLA V2: Learning to Run VLAs Fast, Smooth and Accurate",
  authors: "上海AI Lab",
  venue: "arXiv:2603.20000",
  date: "2026-03-20",
  summary: "实时VLA，在边缘设备(Jetson)上快速流畅运行VLAs。EAGLE-3投机解码+NVFP4量化优化，兼顾精度和速度。适合无人机实时性需求。",
  link: "https://arxiv.org/abs/2603.20000",
  pdf_url: "https://arxiv.org/pdf/2603.20000",
  tags: ["VLA", "Real-time", "Edge AI", "Quantization"],
  importance: "medium"
},
  {
  title: "FocusVLA: Visual Attention Optimization for Efficient Vision-Language-Action Models",
  authors: "字节跳动",
  venue: "arXiv:2603.28740",
  date: "2026-03-28",
  summary: "VLA瓶颈在于如何利用视觉而非视觉质量本身。提出Modality Cascaded Attention消除快捷路径。边缘部署计算优化参考。",
  link: "https://arxiv.org/abs/2603.28740",
  pdf_url: "https://arxiv.org/pdf/2603.28740",
  tags: ["VLA", "Attention", "Edge AI", "Efficiency"],
  importance: "medium"
}
];

export const githubProjects: GitHubProject[] = [
  {
  name: "PX4 Autopilot",
  description: "开源无人机自动驾驶软件，支持多旋翼、固定翼、VTOL等。学术界最流行的无人机研究平台。",
  stars: "11.6k",
  language: "C++",
  link: "https://github.com/PX4/PX4-Autopilot",
  tags: ["PX4", "UAV", "ROS", "Autonomous Flight", "Drone"],
  verified: true
},
  {
  name: "Prometheus (amov-lab)",
  description: "PX4无人机自主飞行综合解决方案，包含目标追踪、集群控制、SLAM等30+应用模块。累计3.1k+ stars。",
  stars: "3.1k",
  language: "C++",
  link: "https://github.com/amov-lab/Prometheus",
  tags: ["PX4", "UAV", "ROS", "Autonomous Flight", "Tracking"],
  verified: true
},
  {
  name: "embodied-drone-agents",
  description: "LLM drone agent系统，使用MAVSDK-Python作为工具，LangGraph编排任务规划，支持自然语言控制无人机。",
  stars: "20",
  language: "Python",
  link: "https://github.com/EmergenceAI/embodied-drone-agents",
  tags: ["LLM", "MAVSDK", "LangGraph", "Agent", "UAV"],
  verified: true
},
  {
  name: "llm-uav (Atmaca)",
  description: "集成Gemma 3 4B与无人机控制，支持自然语言指令，边缘部署。",
  stars: "0",
  language: "Python",
  link: "https://github.com/furkanisikay/llm-uav",
  tags: ["LLM", "UAV", "Edge AI", "NLP"],
  verified: true
},
  {
  name: "MAVLinkMCP",
  description: "MCP (Model Context Protocol) server for LLM与MAVLink无人机的通信，支持通过MCP协议控制PX4无人机。",
  stars: "16",
  language: "Python",
  link: "https://github.com/ion-g-ion/MAVLinkMCP",
  tags: ["MAVLink", "MCP", "PX4", "LLM"],
  verified: true
},
  {
  name: "Awesome-RL-VLA",
  description: "RL+VLA论文汇总：强化学习视觉-语言-动作模型综述。",
  stars: "658",
  language: "Python",
  link: "https://github.com/Denghaoyuan123/Awesome-RL-VLA",
  tags: ["VLA", "RL", "Survey", "Papers"],
  verified: true
},
  {
  name: "Awesome-LLM-Robotics",
  description: "大语言模型/多模态模型在机器人领域的应用论文汇总。",
  stars: "4.4k",
  language: "Python",
  link: "https://github.com/GT-RIPL/Awesome-LLM-Robotics",
  tags: ["LLM", "Robot", "Survey", "Papers"],
  verified: true
},
  {
  name: "Awesome-Aerial-VLN",
  description: "空中视觉-语言导航(Aerial VLN)论文汇总：无人机VLN方向最新研究。",
  stars: "53",
  language: "Python",
  link: "https://github.com/Sautenich/Awesome-Aerial-Vision-Language-Navigation",
  tags: ["UAV", "VLN", "Navigation", "Survey"],
  verified: true
}
];

export const newsItems: NewsItem[] = [
  {
  title: "UAV Imagery + 多模态 LLM 用于农业推理",
  source: "GitHub",
  date: "_2026-05-0",
  summary: "2026.04 | arXiv: 2604.09907 核心：将无人机航拍图像输入多模态 LLM，实现自动化作物表型分析。 意义：展示了 LLM+无人机在精准农业中的实际应用价值。",
  link: "https://github.com/PX4/PX4-Autopilot",
  published_at: "_2026-05-0",
  freshness: "unknown",
  verified: false,
  why_it_matters: "",
  research_axis: "robotics"
},
  {
  title: "NVIDIA GR00T N1.6 + Cosmos Reason 2 发布",
  source: "NVIDIA Newsroom",
  date: "2026-04-01",
  summary: "NVIDIA发布开源物理AI模型GR00T N1.6和Cosmos Reason世界模型，全球合作伙伴推出下一代机器人，机器人的ChatGPT时刻已至。",
  link: "https://nvidianews.nvidia.com/news/nvidia-releases-new-physical-ai-models-as-global-partners-unveil-next-generation-robots",
  published_at: "2026-04-01",
  freshness: "fresh",
  verified: true,
  why_it_matters: "开源物理AI+世界模型对机器人仿真和无人机Sim2Real有直接参考价值",
  research_axis: "robotics"
},
  {
  title: "Unitree B2-W 四足机器人发布",
  source: "Unitree",
  date: "2026-03-25",
  summary: "宇树科技发布B2-W工业四足机器人，负载30kg，续航4小时，支持复杂地形巡检，配备深度相机和激光雷达。",
  link: "https://www.unitree.com.cn/",
  published_at: "2026-03-25",
  freshness: "fresh",
  verified: true,
  why_it_matters: "四足机器人硬件迭代，负载和续航大幅提升，工业巡检应用加速落地",
  research_axis: "robotics"
},
  {
  title: "DJI Air 3S 无人机发布",
  source: "DJI",
  date: "2026-03-28",
  summary: "大疆发布Air 3S，配备1英寸主摄+70mm长焦双摄系统，全向避障，支持APAS 5.0，续航48分钟，面向消费级航拍市场。",
  link: "https://www.dji.com/cn/air-3s",
  published_at: "2026-03-28",
  freshness: "fresh",
  verified: true,
  why_it_matters: "消费级无人机避障和续航持续进化，DJI技术动态",
  research_axis: "drone"
},
  {
  title: "OpenAI 发布 GPT-4.5 API，扩展上下文窗口",
  source: "OpenAI",
  date: "2026-04-02",
  summary: "OpenAI向开发者开放GPT-4.5 API，上下文窗口扩展至200k tokens，定价下调40%，强化函数调用和结构化输出能力。",
  link: "https://openai.com/index/gpt-4-5-launch",
  published_at: "2026-04-02",
  freshness: "fresh",
  verified: true,
  why_it_matters: "LLM API成本下降+长上下文对无人机NL指令解析和任务规划直接利好",
  research_axis: "llm"
}
];

export const researchTrends: Trend[] = [
  {
  icon: "🤖",
  title: "ICML 2026 VLA论文密集爆发",
  description: "PRTS、Move-Then-Operate、RedVLA、CriticVLA四篇ICML VLA论文同时出现"
},
  {
  icon: "🤖",
  title: "VLA安全成为独立方向",
  description: "RedVLA(红队)+VLA Safety Survey+SimpleVLA-Guard形成完整安全研究链"
},
  {
  icon: "📡",
  title: "后训练问题被重视",
  description: "DeLock(锁定现象)+Breaking Lock-In，小数据微调的泛化问题受关注"
},
  {
  icon: "📡",
  title: "目标条件RL兴起",
  description: "PRTS用对比RL替代行为克隆，1670亿token大规模预训练"
},
  {
  icon: "🤖",
  title: "层次化VLA持续演进",
  description: "Move-Then-Operate(双专家)+CriticVLA(两阶段)+Walk With Me(双策略)"
}
];

export const researchStats = {
  totalPapers: 6,
  totalProjects: 8,
  totalNews: 5,
  lastUpdated: "2026-05-04T08:45:45.632819"
};
